baseurl = "https://marsjamudde.nl" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "Marsja Mudde Muziek"
theme = "soho"
DefaultContentLanguage = "nl"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
[pagination]
pagerSize = 5
ignoreErrors = ["error-remote-getjson"]
weight = 2

[languages]
    [languages.nl]
    languageName = "Nederlands"
    readMore = "Lees meer..."
    weight = 1
    [languages.nl.menu]
        [[languages.nl.menu.main]]
        name = "Nieuws / Home"
        identifier = "nieuws"
        weight = 10
        url = "/"

        [[languages.nl.menu.main]]
        name = "Over Marsja Mudde"
        identifier = "about"
        weight = 20
        url = "/about"

        [[languages.nl.menu.main]]
        name = "Programma's"
        identifier = "programmas"
        weight = 30
        url = "/programmas"        

        [[languages.nl.menu.main]]
        name="Ensembles"
        identifier="ensembles"
        weight = 40
        url = "/ensembles"

        [[languages.nl.menu.main]]
        name="Zangles praktijk"
        identifier="zangles"
        weight = 50
        url = "/zangles"

        [[languages.nl.menu.main]]
        name="Workshops"
        identifier="workshops"
        weight = 60
        url = "/workshops"

        [[languages.nl.menu.main]]
        name = "Evenementen overzicht"
        identifier = "events"
        weight = 15
        url = "/events"

        [[languages.nl.menu.main]]
        name = "Oude muziek blog"
        identifier = "blog"
        weight = 80
        url = "/blog"

        [[languages.nl.menu.main]]
        name="Fragmenten"
        identifier="fragmenten"
        weight = 90
        url = "/fragmenten"

        [[languages.nl.menu.main]]
        name="CD's & Boeken"
        identifier="products"
        weight = 100
        url = "/products"

        [[languages.nl.menu.main]]
        name = "Contact"
        identifier = "contact"
        weight = 120
        url = "/contact"

         [[languages.nl.menu.main]]
        name = "Nieuwsbrief"
        identifier = "newsletter"
        weight = 110
        url = "/newsletter"

    [languages.nl.params.translations]
        date = "Datum"
        event = "Evenement"

    [languages.en]
    languageName = "English"
    readMore = "Read more..."
    weight = 2

        [languages.en.menu]
        [[languages.en.menu.main]]
        name = "News / Home"
        identifier = "news"
        weight = 10
        url = "/en/"

        [[languages.en.menu.main]]
        name = "About Marsja Mudde"
        identifier = "about"
        weight = 20
        url = "/en/about/"

        [[languages.en.menu.main]]
        name = "Programmes"
        identifier = "programmas"
        weight = 30
        url = "/en/programmas/"

        [[languages.en.menu.main]]
        name="Ensembles"
        identifier="ensembles"
        weight = 40
        url = "/en/ensembles/"

        [[languages.en.menu.main]]
        name="Teaching practice"
        identifier="zangles"
        weight = 50
        url = "/en/zangles"

        [[languages.en.menu.main]]
        name="Workshops"
        identifier="workshops"
        weight = 60
        url = "/en/workshops"

        [[languages.en.menu.main]]
        name = "Events calendar"
        identifier = "events"
        weight = 15
        url = "/en/events/"

        [[languages.en.menu.main]]
        name = "Early music blog"
        identifier = "blog"
        weight = 80
        url = "/en/blog/"

        [[languages.en.menu.main]]
        name = "Fragments"
        identifier = "fragmenten"
        weight = 90
        url = "/en/fragmenten/"

        [[languages.en.menu.main]]
        name = "CDs & Books"
        identifier = "products"
        weight = 100
        url = "/en/products/"

        [[languages.en.menu.main]]
        name = "Contact"
        identifier = "contact"
        weight = 120
        url = "/en/contact"

        [[languages.en.menu.main]]
        name = "Newsletter"
        identifier = "newsletter"
        weight = 110
        url = "/en/newsletter"


     [languages.en.params.translations]
        date = "Date"
        event = "Event"

[params]
title = "Marsja Mudde Muziek"
author = "Marsja Mudde"
description = "Marsja Mudde - zangeres en docent gespecialiseerd in oude muziek, Hildegard von Bingen, middeleeuwse muziek en gregoriaans. Workshops, zangles en concerten."
customCss = ["css/modern.css"]
# gravatar = "soho@example.com"
images = ["images/profile.png"]
profilePicture = "images/profile.png"
copyright = "Marsja Mudde"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["news"]

  

## Set custom theme color.
## themeColor = "#fc2803"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://nl.linkedin.com/in/marsjamudde"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.x]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.x]
disableInlineCSS = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
# needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
unsafe = true

buildFuture = true